spring.application.name=trackingservice

# enable output with color in the console
spring.output.ansi.enabled=always

# Kafka configuration
kafka.bootstrap-servers=localhost:9092

# configure the kafka Deserializer for the key
kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
