spring.application.name=trackingservice

# enable output with color in the console
spring.output.ansi.enabled=always

# Kafka configuration
kafka.bootstrap-servers=localhost:9092

# configure the kafka deserializer to deserialize the message value as String
# spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# configure the Deserializer Error Handling
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# configure the kafka delegate class after a deserialization error
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# configure the kafka deserializer default value type (NECESSARY FOR JSON DESERIALIZATION!!!)
spring.kafka.consumer.properties.spring.json.value.default.type=dev.lydtech.tracking.event.DispatchPreparing


